#!/usr/bin/env bash

usage-add() {
    cat << EOF
Usage: star add PATH [NAME]
       star a PATH [NAME]

Add a new bookmark.

    PATH
        Relative path to the directory to bookmark.
        e.g. "star add ." will bookmark the current directory

    NAME
        The name of the new bookmark if provided, otherwise it will use the name of the current directory.
        - Must be unique (among all bookmarks)
        - Can contain slashes: "/"
        - Whitespaces will be replaced by a dash: "-"
        - Names with only numeric characters will by prefixed by "dir-"
EOF
}

usage-list() {
    cat << EOF
Usage: star list
       star L

List all bookmarks, by default sorted according to last load (top ones are the last loaded bookmarks).

Listing can be customized either by setting environment variables or by using star-list options.
Use 'star-list --help': its specification also applies to 'star list'.
EOF
}

usage-load() {
    cat << EOF
Usage: star load STAR
       star l STAR

Navigate (cd) into the bookmarked directory.

    STAR
        Should be the name or index of a bookmarked directory (one that is listed using "star list").
EOF
}

usage-rename() {
    cat << EOF
Usage: star rename <STAR> <NEW_STAR_NAME>

Rename an existing bookmark.

    STAR
        Should be the name of a bookmarked directory.

    NEW_STAR_NAME
        The new name of the bookmark.
        - Must be unique (among all bookmarks)
        - Can contain slashes /
EOF
}

usage-remove() {
    cat << EOF
Usage: star remove <STAR> [STAR]...
       star rm <STAR> [STAR]...

Remove one or more bookmarks.

    STAR
        Should be the name of a bookmarked directory.
EOF
}

usage-reset() {
    cat << EOF
Usage: star reset [-f|--force]

Remove all bookmarks and the ".star" directory.

    --force, -f
        Force reset without prompting the user.
EOF
}

usage-config() {
    cat << EOF
Usage: star config

Open the star configuration file in a terminal text editor then apply the updated configuration.

Configuration file:
    If the configuration file does not exist, star will suggest a command to create one from a provided template.

    Location:
        ${_STAR_CONFIG_HOME}/star_config.sh    
    Template location:
        ${_STAR_HOME}/share/star/config/star_config.sh.template

Editor:
    - use the one defined in the environment variable EDITOR
    - else use "nano" if available
    - else use "vi" if available
EOF
}

# the following function could be another implementation of "star config",
# where it does not open the file in an editor, but:
# - without option displays the current configuration
# - else edits the configuration file according to the provided option

# usage-config() {
#     cat << EOF
# Usage: star config [OPTION]

# Display or edit the "star" configuration.

#     (d) default config

#     OPTION
#         list.sort
#             name (d)    Sort according to bookmark's name.
#             loaded      Sort according to bookmark's most recent load (cd)
#         list.order
#             desc (d)    Descending order
#             asc         Ascending order
#         list.index
#             none        No index
#             desc        Descending numeric index
#             asc (d)     Ascending numeric index

#         variables       Whether to enable (yes) or disable (no) the environment variables
#             yes (d)
#             no
# EOF
# }

usage-default() {
    cat << EOF
Usage: star [MODE]

Dynamically bookmark and cd into directories.
Bookmarks are called "stars".

    MODE
        add     Add a new bookmark
        list    List all bookmarks
        load    cd into a bookmarked directory
        rename  Change the name of a bookmark
        remove  Remove a bookmark
        reset   Delete all bookmarks

    Get more information for each mode using:
        star MODE --help
        star help MODE
EOF
}

mode=default

while [[ $# -gt 0 ]]; do
    opt="$1";
    shift;
    # we could remove double quotes
    case "$opt" in
        "--" ) break 2;;
        "-" ) break 2;;
        "-m"|"--mode="* )
            if [[ ${#opt} -eq 2 ]]; then
                mode="$1"
                shift
            else
                mode="${opt#*=}"
            fi
            modes_list=(default add list load rename remove reset config)

            if [[ ! "${modes_list[*]}" =~ (^|[[:space:]])"$mode"($|[[:space:]]) ]]; then
                echo >&2 "Invalid mode: $mode"
                exit 2
            fi
            ;;
        -*|--*)
            echo >&2 "Invalid option: $opt"
            exit 1
            ;;
        *)
            echo >&2 "Invalid argument: $opt"
            exit 1
            ;;
   esac
done

usage-$mode
